services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "./html:/var/www/html"
    ports:
      - "80:80"
