- name: Git clone wizardlab-bind9
  ansible.builtin.git:
    repo: "https://github.com/ashemath/wizardlab-bind9.git"
    dest: "/vagrant/wizardlab-bind9"
    force: yes

- name: Deploy and start the BIND9 server
  ansible.builtin.shell:
    cmd: "docker compose up -d"
    chdir: "/vagrant/wizardlab-bind9"
