---
- name: Deploy netboot.xyz to services
  hosts: services
  become: true

  tasks:
    - name: copy dhcpd.conf
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/dhcpd.conf"
        dest: "/etc/dhcp/dhcpd.conf"
    - name: copy dhcpd.conf
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/etc_defaults_isc-dhcp-server"
        dest: "/etc/defaults/isc-dhcp-server"
    - name: copy dhcpd.conf
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/etc_defaults_tftp-hpa"
        dest: "/etc/defaults/tftpd-hpa"
    - name: install dependencies
      ansible.builtin.apt:
        pkg:
        - ansible 
        - git 
        - apache2
        - isc-dhcp-server
        - tftpd-hpa
    - name: clear out the directory
      ansible.builtin.file:
        path: /opt/netboot.xyz
        state: absent
    - name: Clone the netboot.xyz repository
      ansible.builtin.shell:
        cmd: "git clone \
          https://github.com/netbootxyz/netboot.xyz.git /opt/netboot.xyz"
    - name: run the configuration playbook
      ansible.builtin.shell: 
        cmd: "ansible-playbook -b -i inventory /opt/netboot.xyz/site.yml"
        chdir: /opt/netboot.xyz
    - name: download the .efi
      ansible.builtin.shell:
        cmd: "wget https://boot.netboot.xyz/ipxe/netboot.xyz.efi && systemctl restart tftpd-hpa"
        chdir:  /srv/tftp/
