- name: Install lazy nginx server
  ansible.builtin.apt:
    name: nginx
    state: present

- name: remove isc-dhcp-defaults
  ansible.builtin.file:
    path: "/etc/default/isc-dhcp-server"
    state: absent

- name: remove old dhcpd.conf
  ansible.builtin.file:
    path: /etc/dhcp/dhcpd.conf
    state: absent

- name: Copy over service defaults
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/rocky/files/etc_default_tftpd-hpa"
    dest: "/etc/default/tftpd-hpa"

- name: Copy over service defaults
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/pxe/files/etc_default_isc-dhcp-server"
    dest: "/etc/default/isc-dhcp-server"

- name: create tftp root
  ansible.builtin.file:
    path: "/srv/tftp"
    mode: "0755"
    state: directory

- name: ensure rocky9 tftp folder
  ansible.builtin.file:
    path: "/srv/tftp/rocky9/"
    mode: "0755"
    state: directory

- name: ensure pxe images folder
  ansible.builtin.file:
    path: "/srv/tftp/rocky9/images/pxeboot"
    mode: "0755"
    state: directory

- name: download boot files
  ansible.builtin.get_url:
    url: "{{ rocky_img_url }}/{{ item }}"
    dest: "/srv/tftp/rocky9/images/pxeboot/{{ item }}"
  loop:
    - vmlinuz
    - initrd.img

- name: download ks files
  ansible.builtin.get_url:
    url: "{{ rocky_ks_url }}/{{ item }}"
    dest: "/srv/tftp/rocky9/{{ item }}"
  loop:
    - BOOTX64.EFI
    - grub.cfg
    - grubx64.efi
    - mmx64.efi
      
- name: Configure dhcp.conf
  ansible.builtin.template:
    src: "{{ playbook_dir }}/pxe/templates/pxe_dhcpd.conf.j2"
    dest: "/etc/dhcp/dhcpd.conf"

- name: Ensure dhcp and tftpd are installed
  ansible.builtin.apt:
    pkg:
      - isc-dhcp-server
      - tftpd-hpa

- name: restart PXE services
  ansible.builtin.service:
    name: tftpd-hpa
    state: restarted

- name: restart PXE services
  ansible.builtin.service:
    name: isc-dhcp-server
    state: restarted
