- name: Install dependencies
  ansible.builtin.dnf:
    pkg:
      - epel-release
      - device-mapper-persistent-data 
      - yum-utils
      - lvm2

- name: add key
  ansible.builtin.rpm_key:
    state: present
    key: 'https://download.ceph.com/keys/release.asc'

- name: Install cephadm
  ansible.builtin.dnf:
    name: "https://download.ceph.com/rpm-18.1.3/el9/noarch/cephadm-18.1.3-0.el9.noarch.rpm"


- name: Bootstrap cluster
  ansible.builtin.command:
    cmd: "cephadm bootstrap --mon-ip {{ ansible_host}} --skip-mon-network"
    creates: "/etc/ceph/ceph.conf"
  delegate_to: node0
  run_once: true

