---
- name: Deploy Debian PXE Server with Clonezilla-Live
  hosts: services
- name: Deploy NFS share for Clonezilla.
  ansible.builtin.import_playbook: "{{ playbook_dir }}/pxe/clonezilla_nfs.yml"
- name: Clonezilla based imaging suite
  ansible.builtin.import_playbook: "{{ playbook_dir }}/pxe/clonezilla_pxe.yml"
