---
- name: Deploy Debian PXE with added Clonezilla-live
  hosts: services
  become: yes
  vars:
    next_server_file: "debian-installer/amd64/bootnetx64.efi"
  
  tasks:
  - name: Deploy NFS share for Clonezilla.
    ansible.builtin.import_tasks: "{{ playbook_dir }}/clonezilla/tasks/clonezilla_nfs.yml"
  - name: Clonezilla based imaging suite
    ansible.builtin.import_tasks: "{{ playbook_dir }}/clonezilla/tasks/clonezilla.yml"
