---
- name: Rocky PXE Boot
  hosts: services
  become: yes
  
  tasks:
  - name: include docker
    ansible.builtin.include_role:
      name: docker
    tags:
      - docker
      - always

  - name: Rocky PXE Boot
    ansible.builtin.import_role:
      name: infra

  - name: Rocky PXE Boot
    ansible.builtin.import_role:
      name: rocky
