- name: install nfs server 
  ansible.builtin.apt:
    pkg:
      - nfs-kernel-server
- name: Ensure that a /vagrant/clonezilla/ directory exists
  ansible.builtin.file:
    path: "/vagrant/clonezilla/"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Add relevant nfs configuration.
  ansible.builtin.lineinfile:
    path: "/etc/exports"
    line: "/vagrant/clonezilla \
      192.168.56.0/24(rw,fsid=1,sync,no_root_squash,no_subtree_check)"
    state: present

- name: Restart the nfs service
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
