- name: copy tftp defaults
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/infra/files/etc_defaults_tftp-hpa"
    dest: "/etc/default/tftpd-hpa"
- name: install dependencies
  ansible.builtin.apt:
    pkg:
      - ansible 
      - git 
      - apache2
      - tftpd-hpa
- name: clear out the directory
  ansible.builtin.file:
    path: /opt/netboot.xyz
    state: absent
- name: Clone the netboot.xyz repository
  ansible.builtin.shell:
    cmd: "git clone \
      https://github.com/netbootxyz/netboot.xyz.git /opt/netboot.xyz"
- name: run the configuration playbook
  ansible.builtin.shell: 
    cmd: "ansible-playbook -b -i inventory /opt/netboot.xyz/site.yml"
    chdir: /opt/netboot.xyz
- name: download the .efi
  ansible.builtin.shell:
    cmd: "wget https://boot.netboot.xyz/ipxe/netboot.xyz.efi 
      && systemctl restart tftpd-hpa"
    chdir:  /srv/tftp/
