- name: Deploying dhcpd.conf for PXE
  ansible.builtin.template:
    src: "{{ playbook_dir }}/pxe/templates/pxe_dhcpd.conf.j2"
    dest: "/etc/dhcp/dhcpd.conf"
- name: copy dhcp defaults (eth1 and ipv4 only)
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/infra/files/etc_defaults_isc-dhcp-server"
    dest: "/etc/default/isc-dhcp-server"
- name: install dependencies
  ansible.builtin.apt:
    pkg:
      - isc-dhcp-server
    state: present
- name: reload dhcp
  ansible.builtin.shell: "systemctl restart isc-dhcp-server.service"

